---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      project: teampass
      provider: forge
    name: teampass
  spec:
    replicas: 1
    selector:
      project: teampass
      provider: forge
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 10800
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          project: teampass
          provider: forge
      spec:
        containers:          
          - image: teampass/teampass
            imagePullPolicy: IfNotPresent
            name: teampass
            ports:
            - containerPort: 80
              name: http
              protocol: TCP
            volumeMounts:
            - mountPath: /teampass
              name: claim-teampass
            resources: {}
            terminationMessagePath: /dev/termination-log
          - image: mysql/mysql-server:5.5
            imagePullPolicy: IfNotPresent
            name: mysql
            env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mypass" 
            - name: MYSQL_DATABASE
              value: "teampass"
            - name: MYSQL_PASSWORD
              value: teampass 
            - name: MYSQL_USER
              value: "teampass"
            ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - mountPath: /var/lib/mysql
              name: claim-mysql
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            securityContext: {}
            terminationGracePeriodSeconds: 30
        volumes:
        - name: claim-teampass
          persistentVolumeClaim:
            claimName: claim-teampass
        - name: claim-mysql
          persistentVolumeClaim:
            claimName: claim-mysql
    test: false
    triggers:
    - type: ConfigChange
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: claim-teampass
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    name: claim-mysql
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      expose: "true"
      project: teampass
      provider: forge
    name: teampass
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      project: teampass
      provider: forge
    type: ClusterIP
    
    

